language: ruby
rvm:
  - 2.4.1 # should be in sync with .ruby-version
services: postgresql
addons:
  postgresql: "9.4"
#We don't want the --deployment flag which is added by default
before_install:
  - if ruby -v | grep 2.3.3; then gem update --system 2.6.9; fi #https://github.com/sickill/rainbow/issues/44
  - gem --version
install: bundle install --jobs=3 --retry=3 --without "development production"
before_script:
  - bin/rake db:create db:migrate
script:
  - bundle exec rspec
