language: ruby
rvm:
  - 2.2.0
  - 2.3.3
services: postgresql
addons:
  postgresql: "9.4"
#We don't want the --deployment flag which is added by default
install: bundle install --jobs=3 --retry=3
before_script:
  - bin/rake db:create db:migrate
script:
  - bundle exec rspec
