# version: '2'
# services:
#   elektra:
#     image: sapcc/elektra
#     ports:
#       - "5000:80"
#     environment:
#       POSTGRES_SERVICE_HOST: postgres
#     links: [postgres]
#     command: [script/wait-for-postgres.sh, script/start.sh]
#
#   postgres:
#     image: postgres:9.5


version: '3'
services:
  elektra:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
     - "3000:3000"
    volumes:
     - ../elektra:/home/app/webapp
    links: [postgres]
    command: [script/wait-for-postgres.sh, script/start.sh]
    environment:
      POSTGRES_SERVICE_HOST: postgres
      MONSOON_DB_NAME: elektra_development
      MONSOON_DB_USER: postgres

  postgres:
    image: postgres:9.6
    restart: always
    volumes:
     - ./tmp/postgres-data:/var/lib/postgresql/data
