<%
  options  = " --format #{ENV['CUCUMBER_FORMAT'] || 'pretty'}" 
  options += " --format CI::Reporter::Cucumber --out #{ENV['CI_REPORTS'] || 'features/reports'}" if ENV['HEADLESS']
  options += " -r features" 
%>

default:     <%= options %> --strict --tags ~@wip features/acceptance
acceptance:  <%= options %> --strict --tags ~@wip features/acceptance
integration: <%= options %> --strict --tags ~@wip --tags @javascript features/integration
